apiVersion: v1
kind: Namespace
metadata:
  name: source
---
apiVersion: v1
kind: Namespace
metadata:
  name: target
---
apiVersion: v1
kind: Namespace
metadata:
  name: target2
---
apiVersion: v1
kind: Namespace
metadata:
  name: notused
---
apiVersion: v1
kind: Secret
metadata:
  name: sync
  namespace: source
  labels:
    whisperer.jeffl.es/sync: "true"
  annotations:
    whisperer.jeffl.es/namespaces: "target,target2,missing"
data:
  secret: dG90YWxseSBhIHN1cGVyIGR1cGVyIHNlY3JldCB5b3Ugc2hvdWxkbid0IHRlbGwgYW55b25lCg==
