[package]
name = "whisperer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0.98", features = ["backtrace"] }
axum = "0.8.3"
dotenvy = "0.15.7"
futures = "0.3.31"
gethostname = "1.0.1"
k8s-openapi = { version = "0.25.0", features = ["latest"] }
kube = { version = "1.1.0", features = ["runtime", "config"] }
opentelemetry = "0.29.1"
opentelemetry-otlp = "0.29.0"
opentelemetry-prometheus = "0.29.1"
opentelemetry_sdk = { version = "0.29.0", features = ["rt-tokio"] }
prometheus = "0.14.0"
rand = "0.9.1"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tracing = "0.1.41"
tracing-opentelemetry = "0.30.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "std"] }

[dev-dependencies]
httpmock = { version = "0.8.0-alpha.1", features = ["record"] }
serde_json = "1.0.140"
