[package]
name = "whisperer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.97", features = ["backtrace"] }
axum = "0.8.1"
dotenvy = "0.15.7"
futures = "0.3.31"
gethostname = "1.0.0"
k8s-openapi = { version = "0.24.0", features = ["latest"] }
kube = { version = "0.98.0", features = ["runtime", "config"] }
kube-leader-election = "0.39.0"
opentelemetry = "0.28.0"
opentelemetry-otlp = "0.28.0"
opentelemetry-prometheus = "0.28.0"
opentelemetry_sdk = { version = "0.28.0", features = ["rt-tokio"] }
prometheus = "0.13.4"
rand = "0.9.0"
thiserror = "2.0.12"
tokio = { version = "1.43.0", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["sync"] }
tracing = "0.1.41"
tracing-opentelemetry = "0.29.0"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "std"] }

[dev-dependencies]
httpmock = { version = "0.8.0-alpha.1", features = ["record"] }
serde_json = "1.0.139"
