apiVersion: v1
kind: Namespace
metadata:
  name: source
---
apiVersion: v1
kind: Namespace
metadata:
  name: target
---
apiVersion: v1
kind: Secret
metadata:
  name: sync
  namespace: source
  labels:
    secret-syncer.jeffl.es/sync: "true"
    secret-syncer.jeffl.es/namespaces: "target"
data:
  secret: c2VjcmV0Cg==
