apiVersion: v1
kind: Namespace
metadata:
  name: source
---
apiVersion: v1
kind: Namespace
metadata:
  name: target
---
apiVersion: v1
kind: Namespace
metadata:
  name: target2
---
apiVersion: v1
kind: Namespace
metadata:
  name: notused
---
apiVersion: v1
kind: Secret
metadata:
  name: sync
  namespace: source
  labels:
    secret-syncer.jeffl.es/sync: "true"
  annotations:
    secret-syncer.jeffl.es/namespaces: "target,target2"
data:
  secret: c2VjcmV0LW1vcmUK
